### PR TITLE
Add Wiki Loves Pride

### PR DESCRIPTION
**Pull request by domdomegg**
Edited with campaigns editor commit 1cece7b

### CODE REVIEW

**Comment by domdomegg** [comment]
Oh also I should say it removes two expired campaigns:
- Picture of the Year
- Wiki loves love

**Comment by nicolas-raoul** [comment]
Strangely it seems that Travis did not run on this pull request, despite #6
Any idea why?

**Comment by domdomegg** [comment]
It shows me that Travis did run, both on the PR and master branch:

image

image

Can you double check you can't see these checks - I might have misconfigured the visibility maybe. They should just be public. Think you should also be able to see https://github.com/commons-app/campaigns/pull/12/checks

**Comment by nicolas-raoul** [comment]
Ah yes sorry I thought the check was about GPG. Thanks! :-)

**Pull request merged**
