### PR TITLE
Add JSON Schema and Travis validation

### PR DESCRIPTION
**Pull request by domdomegg**
Wanted to learn the basics of Travis and try setting a super basic script up. Thought I may as well practice on this repo, hopefully should make sure we don't merge invalid JSON files, or slightly trickier to detect valid JSON files which will cause crashes when we try to parse them in the app.

Example of Travis output: https://travis-ci.com/domdomegg/campaigns/builds/106427191

### CODE REVIEW

**Comment by domdomegg** [comment]
To get this working:

1. [Enable Travis](https://travis-ci.com/organizations/commons-app/repositories) for this repository (no other config needed)
2. Merge this PR

**Comment by domdomegg** [comment]
One thing I should prove works is that it does flag issues. Have created two demo branches in my repo:

Invalid JSON:
https://travis-ci.com/domdomegg/campaigns/builds/106381821

Valid JSON, but with value that would error in parsing in the app:
https://travis-ci.com/domdomegg/campaigns/builds/106381768

**Comment by sivaraam** [comment]
This one looks like a good step forward that would help us prevent invalid JSON into the repository.

**Comment by domdomegg** [comment]
I don't have access to this repo - will need someone else (maybe just @misaochan?) to merge. Thanks for reminding me about this PR.

**Comment by nicolas-raoul** [comment]
Sorry I just discovered this!
I haven't tested but even if there is a bug it won't affect production, so let's try :-)

**Pull request merged**
